source 'https://github.com/CocoaPods/Specs.git'
source 'http://ph.benemind.com/diffusion/SPEC/emspecs.git'

target 'MSAppModuleWebApp_Example', :exclusive => true do
  pod 'MSAppModuleWebApp', :path => '../'
end

target 'MSAppModuleWebApp_Tests', :exclusive => true do
  pod 'MSAppModuleWebApp', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
