source 'https://github.com/CocoaPods/Specs.git'
source 'http://ph.benemind.com/diffusion/SPEC/emspecs.git'

target 'MSAppModuleWebApp_Example' do
  pod 'MSAppModuleWebApp', :path => '../'
  pod 'commonLib', :git => 'https://github.com/yanghl/commonLib.git'
end

target 'MSAppModuleWebApp_Tests' do
  pod 'MSAppModuleWebApp', :path => '../'
  pod 'commonLib', :git => 'https://github.com/yanghl/commonLib.git'

end
